### ISSUE TITLE
[SID] Feature Checklist

### ISSUE THREAD

**Issue by MyNameIsKodos** [CollectiveIndustries/StarfleetDelta#40]
- [x] Date
- [X] Time
- [X] Stardate
- [X] UUID
- [X] Texture Display
- [X] Sound Play
- [X] Sound Loop
- [X] Integrated Security Relays with alert lamp and sound
- [x] Location of other agents
- [X] Help command (Gives a notecard list of commands)

**Comment by MyNameIsKodos** [comment]
Overhauling SID into a new system. Closing due to no longer having the system being affiliated with SDQ
